#!/usr/bin/env bash

sudo apt update
sudo apt install build-essential pkg-config libcairo2-dev libgirepository1.0-dev

sudo apt install python3-dev gir1.2-glib-2.0

sudo apt-get install bluez
sudo apt install libdbus-1-dev python3-dbus

