#!/usr/bin/env bash

if find . -type d -name ".venv" -print -quit | grep -q .; then
    echo "[info] .venv exists"
else
    echo "[info] setup .venv"
    python3 -m venv --system-site-package .venv
    echo "[info] install packages"
    python3 -m pip install -e ".[dev]"
fi

python3 ./src/main.py
