#!/usr/bin/env bash

log() {
    echo "[$1] $2"
}

venv_exist() {
    [[ -d ".venv" ]]
}

dbus_exist() {
    python3 -c "import dbus" 2>/dev/null
}

source_venv() {
    source .venv/bin/activate
}

setup_project() {
    if ! venv_exist; then
        log "info" "venv initiated"
        python3 -m venv --system-site-packages .venv
    else
        log "info" ".venv exists"
    fi

    log "info" "venv sourced"
    source_venv

    log "info" "Installing packages"
    python3 -m pip install -e ".[dev]"
}

robot_connected() {
    sudo dmesg | grep -qi "ttyAC0"
}

start_application() {
    log "info" "start kotif-bridge"
    java -jar ./script/kotif-bridge/kotif-bridge-1.0-SNAPSHOT.jar bridge ttyAC0 4711 MowerApi.json &

    log "info" "start kotif-bridge"
    python3 src/main.py &
}

java_exists() {
    command -v java >/dev/null 2>&1
}

java_install() {
    sudo apt update
    sudo apt install default-jdk
}

main() {
    if ! java_exists; then
        java_install
    fi

    if ! dbus_exist; then
        log "info" "installing python-dbus"
        sudo apt install python-dbus
    else
        log "info" "python-dbus installed"
    fi

    setup_project
    log "info" "setup project"

    if ! dbus_exist; then
        log "warning" "python-dbus not reachable from venv"
        return 1
    fi

    if ! robot_connected; then
        log "warning" "robot is not connected"
        return 0
    fi

    start_application
}


main "$@"
